# oc apply -f 04_acm-gitopservice.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-acm
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: resources/gitops_acm/base
    repoURL: https://github.com/ignaciolago/service-mesh-gitops.git
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true