---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: smesh-operator
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: gitops-clusters
      requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: smesh-operator-{{name}}
    spec:
      destination:
        namespace: openshift-gitops
        server: '{{server}}'
      project: default
      source:
        path: resources/03_service_mesh_operators/base
        repoURL: 'https://github.com/ignaciolago/service-mesh-gitops.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: smesh-operator-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - gitops-clusters