---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: import-cluster-sandbox772
  namespace: openshift-gitops
spec:
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: resources/06_openshift/base
    repoURL: https://github.com/ignaciolago/service-mesh-gitops.git
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true