---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: resources/spring-app
    repoURL: https://github.com/ignaciolago/service-mesh-gitops.git
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true