kind: ImportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
  name: cluster1-mesh1
  # namespace: cluster2-mesh1-system
spec:
  importRules:
    - type: NameSelector
      importAsLocal: false
      nameSelector:
        namespace: jump-app-dev
        alias:
          namespace: mesh-test