---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: import-openshift-cluster
  namespace: openshift-gitops
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: service-mesh-poc-appset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/ignaciolago/service-mesh-gitops.git
        targetRevision: dev2
        path: resources/02_import-openshift-cluster
      destination:
        server: '{{cluster}}'