---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: smesh-control-plane-cluster02
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: smesh-control-plane-cluster02-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: smesh-control-plane-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/ignaciolago/service-mesh-gitops.git
        targetRevision: main
        path: resources/smesh_cluster02/base
      destination:
        namespace: openshift-gitops
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: smesh-control-plane-cluster02-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - gitops-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - sandbox772