kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: application-properties
  namespace: spring-app
data:
  application.properties: |-

    application.name=@project.artifactId@
    build.version=@project.version@
    build.timestamp=@timestamp@
