apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 00-namespace.yaml
- 01-configmap.yaml
- 02-deployment.yaml
- 03-service.yaml
- 04-route.yaml
- 05-hpa.yaml
