---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: 02-service-mesh-cluster01
  namespace: openshift-gitops
spec:
  generators:
  - clusters: {}
  - list:
    elements: 
      - cluster: cluster01
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: service-mesh-cluster01-{{cluster}}
    spec:
      project: service-mesh-poc-appset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/ignaciolago/service-mesh-gitops.git
        targetRevision: applicationset
        path: resources/base/02-service-mesh-cluster01
      destination:
        server: '{{url}}'